### ISSUE TITLE
CI broken for MacOS

### ISSUE THREAD

**Issue by bentaculum** [napari/cookiecutter-napari-plugin#193]
With the current version of napari `0.5.4`, after installing the `[testing]` dependencies for testing plugins made from this repo, I get the following error:

```
└─▪ napari
Traceback (most recent call last):
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/lib/python3.10/site-packages/napari/_qt/__init__.py", line 9, in <module>
    from qtpy import API_NAME, QT_VERSION, QtCore
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/lib/python3.10/site-packages/qtpy/__init__.py", line 287, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/lib/python3.10/site-packages/napari/__main__.py", line 574, in main
    _maybe_rerun_with_macos_fixes()
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/lib/python3.10/site-packages/napari/__main__.py", line 452, in _maybe_rerun_with_macos_fixes
    from napari._qt import API_NAME
  File "/Users/gallusse/miniforge3/envs/napari-trackastra/lib/python3.10/site-packages/napari/_qt/__init__.py", line 18, in <module>
    raise ImportError(
ImportError: No Qt bindings could be found.

napari requires either PyQt5 (default) or PySide2 to be installed in the environment.

With pip, you can install either with:
  $ pip install -U 'napari[all]'  # default choice
  $ pip install -U 'napari[pyqt5]'
  $ pip install -U 'napari[pyside2]'

With conda, you need to do:
  $ conda install -c conda-forge pyqt
  $ conda install -c conda-forge pyside2

Our heuristics suggest you are using 'conda' to manage your packages.
```

This also makes the CI in Github actions fail.

**Comment by Czaki** [comment]
it looks like you response `n` on `include_widget_plugin` question when create plugin

**Comment by jni** [comment]
Closing as this repo is deprecated. Use https://github.com/napari/napari-plugin-template instead.
