### ISSUE TITLE
Vanilla cookiecutter CI fails on Windows

### ISSUE THREAD

**Issue by thewtex** [napari/cookiecutter-napari-plugin#24]
`Test with tox` [fails](https://github.com/InsightSoftwareConsortium/napari-itk-io/runs/2461719628?check_suite_focus=true):

```
  py38-windows run-test-pre: PYTHONHASHSEED='169'
  py38-windows run-test: commands[0] | pytest -v --color=yes --cov=napari_itk_io --cov-report=xml
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "D:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\Scripts\pytest.EXE\__main__.py", line 7, in <module>
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
      code = main()
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 143, in main
      config = _prepareconfig(args, plugins)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
      config = pluginmanager.hook.pytest_cmdline_parse(
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\hooks.py", line 286, in __call__
      return self._hookexec(self, self.get_hookimpls(), kwargs)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
      return self._inner_hookexec(hook, methods, kwargs)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
      self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\callers.py", line 203, in _multicall
      gen.send(outcome)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
      config: Config = outcome.get_result()
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\callers.py", line 80, in get_result
      raise ex[1].with_traceback(ex[2])
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\callers.py", line 187, in _multicall
      res = hook_impl.function(*args)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
      self.parse(args)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
      self._preparse(args, addopts=addopts)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
      self.pluginmanager.load_setuptools_entrypoints("pytest11")
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
      plugin = ep.load()
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\importlib\metadata.py", line 77, in load
      module = import_module(match.group('module'))
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\__init__.py", line 7, in <module>
      from .viewer import Viewer  # isort:skip
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\viewer.py", line 3, in <module>
      from .components import ViewerModel
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\components\__init__.py", line 17, in <module>
      from .camera import Camera
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\components\camera.py", line 5, in <module>
      from ..utils.events import EventedModel
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\utils\__init__.py", line 1, in <module>
      from .colormaps import Colormap
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\utils\colormaps\__init__.py", line 2, in <module>
      from .colormap import Colormap
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\utils\colormaps\colormap.py", line 9, in <module>
      from .standardize_color import transform_color
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
      exec(co, module.__dict__)
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\napari\utils\colormaps\standardize_color.py", line 27, in <module>
      from vispy.color import ColorArray, get_color_dict, get_color_names
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\vispy\color\__init__.py", line 12, in <module>
      from .colormap import (Colormap, BaseColormap,  # noqa
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\vispy\color\colormap.py", line 15, in <module>
      import vispy.gloo
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\vispy\gloo\__init__.py", line 47, in <module>
      from . import gl  # noqa
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\vispy\gloo\gl\__init__.py", line 231, in <module>
      from . import gl2 as default_backend  # noqa
    File "d:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\lib\site-packages\vispy\gloo\gl\gl2.py", line 31, in <module>
      _lib = ctypes.windll.opengl32
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\ctypes\__init__.py", line 443, in __getattr__
      dll = self._dlltype(name)
    File "c:\hostedtoolcache\windows\python\3.8.9\x64\lib\ctypes\__init__.py", line 373, in __init__
      self._handle = _dlopen(self._name, mode)
  FileNotFoundError: Could not find module 'opengl32' (or one of its dependencies). Try using the full path with constructor syntax.
  ERROR: InvocationError for command 'D:\a\napari-itk-io\napari-itk-io\.tox\py38-windows\Scripts\pytest.EXE' -v --color=yes --cov=napari_itk_io --cov-report=xml (exited with code 1)
```

**Comment by tlambert03** [comment]
huh ... strange.  In our tests, we do actually build the template with [pytest-cookies](https://pypi.org/project/pytest-cookies/), and run its tox tests (e.g. [here](https://github.com/napari/cookiecutter-napari-plugin/runs/2462329737?check_suite_focus=true#step:6:52)).  will see what I can learn

**Comment by thewtex** [comment]
thanks @tlambert03 !

**Comment by tlambert03** [comment]
Hey @thewtex, looks like this was caused by an upstream branch name change at vispy (which is where we're pulling the window opengl fix from).  Could you try just rerunning your workflow when you get a moment?

**Comment by thewtex** [comment]
Hey @tlambert03 , yes that did it, thanks for looking into it!
